name: Build

on:
  push:
    branches:    
      - main
  pull_request:
  schedule:
    - cron: '35 6 * * *'

jobs:
  check_release:
    name: "Check if we should start a new build job for grpcio based on latest release"
    outputs:
      should_build: ${{ steps.profiler_version.outputs.should_build }}
      latest_version: ${{ steps.profiler_version.outputs.current_version }}
    runs-on: ubuntu-latest
    steps:
      - name: "Get latest GitHub release for this repo"
        id: get_release
        run: |
          latestRelease="$(gh api graphql -F owner=$OWNER -F name=$REPO -f query='
            query($name: String!, $owner: String!) {
              repository(owner: $owner, name: $name) {
                releases(last: 1, orderBy: { field: CREATED_AT, direction: ASC }) {
                  nodes { tagName }
                }
              }
            }' --jq '.data.repository.releases.nodes[0].tagName')"
          echo "release=\"$latestRelease\"" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Check latest available grpcio release
        id: profiler_version
        run: |
          LATEST_VERSION=$(pip3 index versions --no-binary google-cloud-profiler google-cloud-profiler | grep google-cloud-profiler | sed -E 's/google-cloud-profiler \(([0-9.]+)\)/\1/')
          echo "Latest google-cloud-profiler version on PyPI: $GRPCIO_LATEST_VERSION"
          echo "current_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          
          LATEST_RELEASE="${{ steps.get_release.outputs.release }}"
          if [[ $LATEST_RELEASE == $LATEST_VERSION ]]; then
            echo "We already have a release for $LATEST_RELEASE. Skipping build."
            echo "should_build=0" >> $GITHUB_OUTPUT
          else
            echo "Latest release $LATEST_RELEASE is outdated, starting build for $LATEST_VERSION"
            echo "should_build=1" >> $GITHUB_OUTPUT
          fi
          echo "should_build=1" >> $GITHUB_OUTPUT
  
  build_wheels:
    name: Build ${{ matrix.package }} wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - "macOS-12"
          # - "ubuntu-22.04"
        package: [ "google-cloud-profiler" ]

    needs: [check_release]
    if: needs.check_release.outputs.should_build == '1'
    steps:
      # Used to host cibuildwheel
      - uses: actions/setup-python@v3
      
      - name: Download latest ${{ matrix.package }} stable tarball
        run: |
          pip download --no-binary ${{ matrix.package }} ${{ matrix.package }}==${{ needs.check_release.outputs.latest_version }}
          tar xf *.tar.gz
          
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.12.0

      - name: Build wheels
        run: |
          cd ${{ matrix.package }}-*/
          python -m cibuildwheel --output-dir ../wheelhouse
        env:
          CIBW_ARCHS_LINUX: "auto"
          CIBW_ARCHS_MACOS: "arm64 universal2"
          CIBW_BUILD_FRONTEND: "build"
          # Disable building PyPy wheels on all platforms
          CIBW_SKIP: "pp*"
          CIBW_TEST_SKIP: "*-*linux_{aarch64}"
          CIBW_PROJECT_REQUIRES_PYTHON: "<3.11"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ matrix.package }} ${{ needs.check_release.outputs.latest_version }}"
          tag_name: ${{ needs.check_release.outputs.latest_version }}
          files: ./wheelhouse/*.whl
          body: "Apple Silicon built binaries for the ${{ matrix.package }} ${{ needs.check_release.outputs.latest_version }} Python library."
