name: Build

on:
  push:
    branches:    
      - main
  pull_request:
#   schedule:
#     - cron: '35 5 * * *'

jobs:
  check_release:
    name: "Check if we should start a new build job for grpcio based on latest release"
    outputs:
      should_build: ${{ steps.profiler_version.outputs.should_build }}
      latest_version: ${{ steps.profiler_version.outputs.current_version }}
    runs-on: ubuntu-latest
    steps:
      - id: get_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Check latest available grpcio release
        id: profiler_version
        run: |
          LATEST_VERSION=$(pip3 index versions --no-binary google-cloud-profiler google-cloud-profiler | grep google-cloud-profiler | sed -E 's/google-cloud-profiler \(([0-9.]+)\)/\1/')
          echo "Latest google-cloud-profiler version on PyPI: $GRPCIO_LATEST_VERSION"
          echo "current_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          
          LATEST_RELEASE="${{ steps.get_release.outputs.release }}"
          if [[ $LATEST_RELEASE == $LATEST_VERSION && false ]]; then
            echo "We already have a release for $LATEST_RELEASE. Skipping build."
            echo "should_build=0" >> $GITHUB_OUTPUT
          else
            echo "Latest release $LATEST_RELEASE is outdated, starting build for $LATEST_VERSION"
            echo "should_build=1" >> $GITHUB_OUTPUT
          fi
  
  build_wheels:
    name: Build ${{ matrix.package }} wheels on ${{ matrix.os }}, for Python ${{ matrix.python_build_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-22.04" ]
        python_build_version: [ "cp38", "cp39", "cp310" ]
        package: [ "google-cloud-profiler" ]

    needs: [check_release]
    if: needs.check_release.outputs.should_build == '1'
    steps:
      # Used to host cibuildwheel
      - uses: actions/setup-python@v3
      
      - name: Download latest ${{ matrix.package }} stable tarball
        run: |
          pip download --no-binary ${{ matrix.package }} ${{ matrix.package }}==${{ needs.check_release.outputs.latest_version }}
          tar xf *.tar.gz
          
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.12.0

      - name: Build wheels
        run: |
          cd ${{ matrix.package }}-*/
          python -m cibuildwheel --output-dir ../wheelhouse
        env:
          CIBW_ARCHS_LINUX: "auto aarch64"
          CIBW_TEST_SKIP: "*-*linux_{aarch64}"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ matrix.package }} ${{ needs.check_release.outputs.latest_version }}"
          tag_name: ${{ needs.check_release.outputs.latest_version }}
          files: ./wheelhouse/*.whl
          body: "Apple Silicon built binaries for the ${{ matrix.package }} ${{ needs.check_release.outputs.latest_version }} Python library."
